volumes:
  postgres_data: {}
  redis_data: {}

services:
  db:
    image: "postgres:16"
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - stack.env
    environment:
      - TZ=Europe/Moscow
    ports:
      - 5432:5432
  redis:
    image: "redis:7.2.5-alpine"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    environment:
      - TZ=Europe/Moscow
  api:
    image: ghcr.io/larek-tech/innohack/control:dev
    build:
      context: backend/.
      dockerfile: Dockerfile
    restart: always
    command: ./main
    ports:
      - 8080:8000
    depends_on:
      - db
      - redis
    env_file:
      - stack.env
    environment:
      - TZ=Europe/Moscow
      - DOCKER_MODE=True

