// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailAccount struct {
	UserID    int64
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type UserProfile struct {
	ID        int64
	Email     string
	FirstName string
	LastName  string
	OtpSecret string
	Verified  pgtype.Bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type UserSession struct {
	ID        int64
	SessionID string
	UserAgent string
	IsValid   bool
	UserID    int64
	CreatedAt pgtype.Timestamp
}

type YandexOauth struct {
	UserID      int64
	AccessToken string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}
