name: Go-Docker

on:
  push:
      paths:
      - 'backend/**'

jobs:
  build_and_push:
    runs-on: [self-hosted]
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract branch name and commit hash
      id: extract_branch
      shell: bash
      run: |
        # Extract the last part of the branch name
        BRANCH_NAME=$(echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" | awk -F'/' '{print $NF}')

        # Get the first 7 characters of the commit hash
        COMMIT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-7)

        # Combine branch name and commit hash
        TAG="${BRANCH_NAME}-${COMMIT_HASH}"

        # Output the tag to be used in the next steps
        echo "tag=${TAG}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: backend/
        file: Dockerfile
        platforms: linux/amd64
        tags: ghcr.io/larek-tech/innohack/control:${{ steps.extract_branch.outputs.tag }}
        push: true
